name: Docker Image CI for PHP 8.4

on:
  push:
    branches:
      - production
  schedule:
    - cron: "20 3 * * 0"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: production
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: sigblue
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push with Alpine 3.21
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags:   |
         sigblue/nginx-php:84
         sigblue/nginx-php:84-alpine-3.21
       build-args:  |
         ALPINE_VERSION=3.21
         V=84
    - name: Build and push with Alpine 3.22
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags:   |
         sigblue/nginx-php:84-alpine-3.22
       build-args:  |
         ALPINE_VERSION=3.22
         V=84
    - name: Build and push with Alpine 3.23
      uses: docker/build-push-action@v3
      with:
       context: .
       push: true
       tags:   |
         sigblue/nginx-php:84-alpine-3.23
       build-args:  |
         ALPINE_VERSION=3.23
         V=84

